### ISSUE TITLE
MA/MFA Spatial Performance and Design

### ISSUE THREAD

**Issue by callmeswee** [NYUAD-IM/Graduate-Programs#4]
https://www.aaschool.ac.uk/academicprogrammes/postgraduate/spatial-performance-design

**Comment by periode** [comment]
Hey Sree! Thanks for pointing it out. Can you open up a pull request for this please?

**Comment by callmeswee** [comment]
This got caught in the haystack, sorry Pierre!

I've opened a pull request!
Sree
